#-------------------------------------------------------------------------------
# Copyright 2019 Dominik Salvet
# github.com/dominiksalvet/template
#-------------------------------------------------------------------------------

os: linux
dist: xenial
language: minimal

jobs:
  include:
    - stage: Stage
      name: Name
      script: true
